packages:
  - packages/*
  - apps/*
  - docs

catalog:
  '@antfu/eslint-config': ^7.7.3
  '@clack/prompts': ^1.1.0
  '@faker-js/faker': ^10.3.0
  '@iconify/json': ^2.2.450
  '@iconify/vue': ^5.0.0
  '@stylistic/stylelint-config': ^4.0.0
  '@types/node': ^25.5.0
  '@types/nprogress': ^0.2.3
  '@types/qs': ^6.15.0
  '@unocss/eslint-plugin': ^66.6.6
  '@vitejs/plugin-vue': ^6.0.5
  '@vitejs/plugin-vue-jsx': ^5.1.5
  '@vue/tsconfig': ^0.9.0
  autoprefixer: ^10.4.27
  axios: ^1.13.6
  boxen: ^8.0.1
  dayjs: ^1.11.20
  eruda: ^3.4.3
  eslint: ^10.0.3
  http-server: ^14.1.1
  lint-staged: ^16.4.0
  mitt: ^3.0.1
  npm-run-all2: ^8.0.4
  nprogress: ^0.2.0
  picocolors: ^1.1.1
  pinia: ^3.0.4
  postcss: ^8.5.8
  postcss-nested: ^7.0.2
  qs: ^6.15.0
  sass-embedded: ^1.98.0
  simple-git-hooks: ^2.13.1
  stylelint: ^17.4.0
  stylelint-config-recess-order: ^7.6.1
  stylelint-config-standard-scss: ^17.0.0
  stylelint-config-standard-vue: ^1.0.0
  stylelint-scss: ^7.0.0
  svgo: ^4.0.1
  taze: ^19.10.0
  tsx: ^4.21.0
  typescript: ^5.9.3
  unocss: ^66.6.6
  unplugin-auto-import: ^21.0.0
  unplugin-turbo-console: ^2.3.0
  unplugin-vue-components: ^31.0.0
  vconsole: ^3.15.1
  vite: ^8.0.0
  vite-plugin-archiver: ^0.2.0
  vite-plugin-banner: ^0.8.1
  vite-plugin-compression2: ^2.5.2
  vite-plugin-env-parse: ^1.0.15
  vite-plugin-fake-server: ^2.2.2
  vite-plugin-pages: ^0.33.3
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-vue-devtools: ^8.1.0
  vite-plugin-vue-layouts-next: ^2.0.1
  vitepress: ^1.6.4
  vitepress-plugin-comment-with-giscus: ^1.1.15
  vue: ^3.5.30
  vue-router: ^5.0.3
  vue-tsc: ^3.2.5
  pinia-plugin-persistedstate: ^4.7.1
