/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoButton: typeof import('./../components/DemoButton/index.vue')['default']
    FsIcon: typeof import('@fantastic-startkit/components')['FsIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const DemoButton: typeof import('./../components/DemoButton/index.vue')['default']
  const FsIcon: typeof import('@fantastic-startkit/components')['FsIcon']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}